In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
import numpy as np

In [11]:
ls

2hy_Wine Quality EDA, ML.ipynb  data_wrangling_json/
3hy_Wine Quality EDA, ML.ipynb  hy_Wine Quality EDA, ML.ipynb
Correlates of War Project/      mini_projects/
PISA_2015_MATH.csv              pandas-videos/
PISA_2015_READING.csv           red_wine_quality.csv
PISA_2015_SCIENCE.csv           white_wine_quality.csv
Untitled.ipynb                  wine_quality_modified.csv
Untitled1.ipynb                 winequality-white.csv
capstone_project/


In [39]:
data=pd.read_csv('winequality-white.csv', delimiter=';')

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
fixed acidity           4898 non-null float64
volatile acidity        4898 non-null float64
citric acid             4898 non-null float64
residual sugar          4898 non-null float64
chlorides               4898 non-null float64
free sulfur dioxide     4898 non-null float64
total sulfur dioxide    4898 non-null float64
density                 4898 non-null float64
pH                      4898 non-null float64
sulphates               4898 non-null float64
alcohol                 4898 non-null float64
quality                 4898 non-null int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


In [41]:

for feature in data.keys():
    step=1.5*((np.percentile(data[feature], q=75))-(np.percentile(data[feature], q=25)))
    lower_bound=(np.percentile(data[feature], q=25))-step
    upper_bound=(np.percentile(data[feature], q=75))+step
    data.drop(list(data.loc[data[feature]<lower_bound].index)+
              list(data.loc[data[feature]>upper_bound].index), inplace=True)

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3811 entries, 0 to 4897
Data columns (total 12 columns):
fixed acidity           3811 non-null float64
volatile acidity        3811 non-null float64
citric acid             3811 non-null float64
residual sugar          3811 non-null float64
chlorides               3811 non-null float64
free sulfur dioxide     3811 non-null float64
total sulfur dioxide    3811 non-null float64
density                 3811 non-null float64
pH                      3811 non-null float64
sulphates               3811 non-null float64
alcohol                 3811 non-null float64
quality                 3811 non-null int64
dtypes: float64(11), int64(1)
memory usage: 387.1 KB


In [52]:
X3 = data.iloc[:, :-1].values
y3 = data.iloc[:, 11].values

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size = 0.2, random_state = 42)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train3 = sc.fit_transform(X_train3)
X_test3 = sc.transform(X_test3)

In [53]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 5)
X_train3 = pca.fit_transform(X_train3)
X_test3 = pca.transform(X_test3)
explained_variance = pca.explained_variance_ratio_

In [47]:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
import scipy.stats as stats
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
from matplotlib import rcParams
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [48]:
# KNN

knn_cv = GridSearchCV(KNeighborsClassifier(), param_grid={'n_neighbors': np.arange(1, 50)}, cv=5)
knn_cv.fit(X_train, y_train)
print("Accuracy: {}".format(knn_cv.score(X_test, y_test)))
print("Tuned Model Parameters: {}".format(knn_cv.best_params_))

Accuracy: 0.6225425950196593
Tuned Model Parameters: {'n_neighbors': 1}


In [49]:
# SVM

from sklearn.svm import SVC
Cs = [0.001, 0.01, 0.1, 1, 10]
gammas = [0.001, 0.01, 0.1, 1]
param_grid = {'C': Cs, 'gamma' : gammas}
svm=SVC(kernel='linear')
gs = GridSearchCV(svm, param_grid, cv=5)

# Fit to the training set
gs.fit(X_train, y_train)

# Predict the labels of the test set: y_pred
y_pred = gs.predict(X_test)

# Compute and print metrics
print("Accuracy: {}".format(gs.score(X_test, y_test)))
print("Tuned Model Parameters: {}".format(gs.best_params_))

Accuracy: 0.5307994757536042
Tuned Model Parameters: {'C': 1, 'gamma': 0.001}


In [50]:
# Kernel SVM

Cs = [0.001, 0.01, 0.1, 1, 10]
gammas = [0.001, 0.01, 0.1, 1]
param_grid = {'C': Cs, 'gamma' : gammas}
svm=SVC(kernel='rbf')
gs = GridSearchCV(svm, param_grid, cv=5)

# Fit to the training set
gs.fit(X_train, y_train)

# Predict the labels of the test set: y_pred
y_pred = gs.predict(X_test)

# Compute and print metrics
print("Accuracy: {}".format(gs.score(X_test, y_test)))
print("Tuned Model Parameters: {}".format(gs.best_params_))

Accuracy: 0.6186107470511141
Tuned Model Parameters: {'C': 10, 'gamma': 1}


In [51]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
cm=confusion_matrix(y_test, y_pred)
ac=accuracy_score(y_test, y_pred)
print('confusion_matrix:\n {}\n\n\naccuracy_score: {}'.format(cm, ac))

confusion_matrix:
 [[  0  10   3   2]
 [  0 128  89   4]
 [  0  93 214  56]
 [  0  17  85  62]]


accuracy_score: 0.5294888597640891
